### PR TITLE
[WIP] Simple logging

### PR DESCRIPTION
**Pull request by dmitrytrager**
WARNING: Experimental features. NOT FOR MERGE.

### CODE REVIEW

**Comment by dmitrytrager** [comment]
@t-harps this is a tempropary PR for actioncable logging
related review app is here: https://coposition-staging-pr-650.herokuapp.com

I can see that there are no log messages on client side. Any ideas why?

**Comment by t-harps** [comment]
Not sure, should those logs appear in the heroku logs? If so in order to enable those kinds of logs we need to add the rails_12factor gem to the staging environment, at the moment we only have it on development and production, I think this will give us the full logs. Also could you reopen this PR to DEV instead of MASTER.

**Comment by dmitrytrager** [comment]
@t-harps there is no point to reopen since I'm not going to merge this PR. I need this only for review app to exist.

These logs should appear in browser console. It's a basic debug tool for front-end code. Why do we need rails_12factor for this to work?

**Comment by dmitrytrager** [comment]
Rails team tries to figure out if it's framework related or puma related: https://github.com/rails/rails/issues/28362.

I'm going to update some dependencies within another PR and close this one.

**Pull request closed without merging**
